"""SelfTool: runtime inspection and configuration tuning for the agent loop."""

from __future__ import annotations

import time
from typing import TYPE_CHECKING, Any

from loguru import logger

from nanobot.agent.subagent import SubagentStatus
from nanobot.agent.tools.base import Tool

if TYPE_CHECKING:
    from nanobot.agent.loop import AgentLoop


def _has_real_attr(obj: Any, key: str) -> bool:
    """Check if obj has a real (explicitly set) attribute, not auto-generated by mock."""
    if isinstance(obj, dict):
        return key in obj
    d = getattr(obj, "__dict__", None)
    if d is not None and key in d:
        return True
    for cls in type(obj).__mro__:
        if key in cls.__dict__:
            return True
    return False


class SelfTool(Tool):
    """Inspect and tune the agent loop's runtime configuration."""

    BLOCKED = frozenset({
        # Core infrastructure
        "bus", "provider", "_running", "tools",
        # Config management
        "_config_defaults", "_runtime_vars",
        "_critical_tool_backup", "_config_dirty",
        # Subsystems
        "subagents", "runner", "sessions", "consolidator",
        "dream", "auto_compact", "context", "commands",
        # Sensitive runtime state (credentials, message routing, task tracking)
        "_mcp_servers", "_mcp_stacks", "_pending_queues",
        "_session_locks", "_active_tasks", "_background_tasks",
    })

    _DENIED_ATTRS = frozenset({
        "__class__", "__dict__", "__bases__", "__subclasses__", "__mro__",
        "__init__", "__new__", "__reduce__", "__getstate__", "__setstate__",
        "__del__", "__call__", "__getattr__", "__setattr__", "__delattr__",
        "__code__", "__globals__", "func_globals", "func_code",
        "__wrapped__", "__closure__",
    })

    RESTRICTED: dict[str, dict[str, Any]] = {
        "max_iterations":        {"type": int, "min": 1,   "max": 100},
        "context_window_tokens": {"type": int, "min": 4096, "max": 1_000_000},
        "model":                 {"type": str, "min_len": 1},
    }

    _MAX_VALUE_ELEMENTS = 1024
    _MAX_RUNTIME_KEYS = 64

    def __init__(self, loop: AgentLoop, modify_allowed: bool = True) -> None:
        self._loop = loop
        self._modify_allowed = modify_allowed
        self._channel = ""
        self._chat_id = ""

    def __deepcopy__(self, memo: dict[int, Any]) -> SelfTool:
        cls = self.__class__
        result = cls.__new__(cls)
        memo[id(self)] = result
        result._loop = self._loop
        result._modify_allowed = self._modify_allowed
        result._channel = self._channel
        result._chat_id = self._chat_id
        return result

    def set_context(self, channel: str, chat_id: str) -> None:
        self._channel = channel
        self._chat_id = chat_id

    @property
    def name(self) -> str:
        return "self"

    @property
    def description(self) -> str:
        base = (
            "Inspect and modify your own runtime state. "
            "Use 'inspect' (with or without key) to view config values. "
            "Use 'modify' to change config values.\n"
            "Available top-level keys: max_iterations, context_window_tokens, model, "
            "workspace, _last_usage, provider_retry_mode, max_tool_result_chars. "
            "Use 'inspect' without key to see all config values at once."
        )
        if not self._modify_allowed:
            base += "\nREAD-ONLY MODE: modify is disabled."
        else:
            base += (
                "\nIMPORTANT: Before modifying state, predict the potential impact. "
                "If the operation could cause crashes or instability "
                "(e.g. changing model), warn the user first."
            )
        return base

    @property
    def parameters(self) -> dict[str, Any]:
        return {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "enum": ["inspect", "modify"],
                    "description": "Action to perform",
                },
                "key": {
                    "type": "string",
                    "description": "Dot-path for inspect/modify. Examples: 'max_iterations', 'workspace', 'provider_retry_mode'. "
                    "For inspect without key, shows all config values.",
                },
                "value": {"description": "New value (for modify). Type must match target (int for max_iterations/context_window_tokens, str for model)."},
            },
            "required": ["action"],
        }

    def _audit(self, action: str, detail: str) -> None:
        session = f"{self._channel}:{self._chat_id}" if self._channel else "unknown"
        logger.info("self.{} | {} | session:{}", action, detail, session)

    def _mark_dirty(self) -> None:
        self._loop._config_dirty = True

    # ------------------------------------------------------------------
    # Path resolution
    # ------------------------------------------------------------------

    def _resolve_path(self, path: str) -> tuple[Any, str | None]:
        parts = path.split(".")
        obj = self._loop
        for part in parts:
            if part in self._DENIED_ATTRS or part.startswith("__"):
                return None, f"'{part}' is not accessible"
            if part in self.BLOCKED:
                return None, f"'{part}' is not accessible"
            try:
                if isinstance(obj, dict):
                    if part in obj:
                        obj = obj[part]
                    else:
                        return None, f"'{part}' not found in dict"
                else:
                    obj = getattr(obj, part)
            except (KeyError, AttributeError) as e:
                return None, f"'{part}' not found: {e}"
        return obj, None

    @staticmethod
    def _validate_key(key: str | None, label: str = "key") -> str | None:
        if not key or not key.strip():
            return f"Error: '{label}' cannot be empty or whitespace"
        return None

    # ------------------------------------------------------------------
    # Smart formatting
    # ------------------------------------------------------------------

    @staticmethod
    def _format_status(st: SubagentStatus, indent: str = "  ") -> str:
        elapsed = time.monotonic() - st.started_at
        tool_summary = ", ".join(
            f"{e.get('name', '?')}({e.get('status', '?')})" for e in st.tool_events[-5:]
        ) or "none"
        lines = [
            f"{indent}phase: {st.phase}, iteration: {st.iteration}, elapsed: {elapsed:.1f}s",
            f"{indent}tools: {tool_summary}",
            f"{indent}usage: {st.usage or 'n/a'}",
        ]
        if st.error:
            lines.append(f"{indent}error: {st.error}")
        if st.stop_reason:
            lines.append(f"{indent}stop_reason: {st.stop_reason}")
        return "\n".join(lines)

    @staticmethod
    def _format_value(val: Any, key: str = "") -> str:
        if val is None:
            return f"{key}: None" if key else "None"
        if isinstance(val, (bool, int, float, str)):
            return f"{key}: {val!r}" if key else repr(val)
        if isinstance(val, SubagentStatus):
            header = f"Subagent [{val.task_id}] '{val.label}'"
            detail = SelfTool._format_status(val, "  ")
            return f"{header}\n  task: {val.task_description}\n{detail}"
        if hasattr(val, "_running_tasks") and isinstance(getattr(val, "_running_tasks"), dict):
            statuses = getattr(val, "_task_statuses", None)
            if statuses and isinstance(statuses, dict) and len(statuses) > 0:
                return SelfTool._format_value(statuses, key)
            tasks = val._running_tasks
            return f"subagents: {len(tasks)} running — {list(tasks.keys())[:10]}"
        if callable(val):
            return f"<method {key}>" if key else "<callable>"
        if isinstance(val, dict):
            first_val = next(iter(val.values()), None)
            if val and isinstance(first_val, SubagentStatus):
                prefix = f"{key}: " if key else ""
                lines = [f"{prefix}{len(val)} subagent(s):"]
                for tid, st in val.items():
                    detail = SelfTool._format_status(st, "    ")
                    lines.append(f"  [{tid}] '{st.label}'\n{detail}")
                return "\n".join(lines)
            r = repr(val)
            if len(r) > 2000:
                r = r[:2000] + "... (truncated)"
            return f"{key}: {r}" if key else r
        if isinstance(val, (list, tuple)):
            preview = repr(val[:20])
            if len(val) > 20:
                preview = preview.rstrip("]") + f", ...] ({len(val)} items)"
            return f"{key}: {preview}" if key else preview
        if hasattr(val, "tool_names"):
            names = val.tool_names
            return f"tools: {len(names)} registered — {names}"
        attrs = [a for a in dir(val) if not a.startswith("_") and not callable(getattr(val, a, None))]
        cls_name = type(val).__name__
        if attrs:
            return f"<{cls_name}> attributes: {attrs[:20]}"
        return f"<{cls_name}>"

    # ------------------------------------------------------------------
    # Action dispatch
    # ------------------------------------------------------------------

    async def execute(
        self,
        action: str,
        key: str | None = None,
        value: Any = None,
        **_kwargs: Any,
    ) -> str:
        if action == "inspect":
            return self._inspect(key)
        if not self._modify_allowed:
            return "Error: modify is disabled (self_modify is False)"
        if action == "modify":
            return self._modify(key, value)
        return f"Unknown action: {action}"

    # -- inspect --

    def _inspect(self, key: str | None) -> str:
        if not key:
            return self._inspect_all()
        top = key.split(".")[0]
        if top in self._DENIED_ATTRS or top.startswith("__"):
            return f"Error: '{top}' is not accessible"
        obj, err = self._resolve_path(key)
        if err:
            return f"Error: {err}"
        if "." not in key and not _has_real_attr(self._loop, key):
            return f"Error: '{key}' not found"
        return self._format_value(obj, key)

    def _inspect_all(self) -> str:
        loop = self._loop
        parts: list[str] = []
        # RESTRICTED keys with validation
        for k in self.RESTRICTED:
            parts.append(f"{k}: {getattr(loop, k, None)!r}")
        # Other useful top-level keys shown in description
        for k in ("workspace", "provider_retry_mode", "max_tool_result_chars"):
            if _has_real_attr(loop, k):
                parts.append(f"{k}: {getattr(loop, k, None)!r}")
        rv = loop._runtime_vars
        if rv:
            rv_repr = repr(rv)
            if len(rv_repr) > 2000:
                rv_repr = rv_repr[:2000] + "... (truncated)"
            parts.append(f"_runtime_vars: {rv_repr}")
        return "\n".join(parts)

    # -- modify --

    def _modify(self, key: str | None, value: Any) -> str:
        if err := self._validate_key(key):
            return err
        top = key.split(".")[0]
        if top in self.BLOCKED or top in self._DENIED_ATTRS or top.startswith("__"):
            self._audit("modify", f"BLOCKED {key}")
            return f"Error: '{key}' is protected and cannot be modified"
        if "." in key:
            parent_path, leaf = key.rsplit(".", 1)
            if leaf in self._DENIED_ATTRS or leaf.startswith("__"):
                self._audit("modify", f"BLOCKED leaf '{leaf}'")
                return f"Error: '{leaf}' is not accessible"
            parent, err = self._resolve_path(parent_path)
            if err:
                return f"Error: {err}"
            if isinstance(parent, dict):
                parent[leaf] = value
            else:
                setattr(parent, leaf, value)
            self._audit("modify", f"{key} = {value!r}")
            self._mark_dirty()
            return f"Set {key} = {value!r}"
        if key in self.RESTRICTED:
            return self._modify_restricted(key, value)
        return self._modify_free(key, value)

    def _modify_restricted(self, key: str, value: Any) -> str:
        spec = self.RESTRICTED[key]
        expected = spec["type"]
        if expected is int and isinstance(value, bool):
            return f"Error: '{key}' must be {expected.__name__}, got bool"
        if not isinstance(value, expected):
            try:
                value = expected(value)
            except (ValueError, TypeError):
                return f"Error: '{key}' must be {expected.__name__}, got {type(value).__name__}"
        old = getattr(self._loop, key)
        if "min" in spec and value < spec["min"]:
            return f"Error: '{key}' must be >= {spec['min']}"
        if "max" in spec and value > spec["max"]:
            return f"Error: '{key}' must be <= {spec['max']}"
        if "min_len" in spec and len(str(value)) < spec["min_len"]:
            return f"Error: '{key}' must be at least {spec['min_len']} characters"
        setattr(self._loop, key, value)
        self._audit("modify", f"{key}: {old!r} -> {value!r}")
        self._mark_dirty()
        return f"Set {key} = {value!r} (was {old!r})"

    def _modify_free(self, key: str, value: Any) -> str:
        if _has_real_attr(self._loop, key):
            old = getattr(self._loop, key)
            setattr(self._loop, key, value)
            self._audit("modify", f"{key}: {old!r} -> {value!r}")
            self._mark_dirty()
            return f"Set {key} = {value!r} (was {old!r})"
        if callable(value):
            self._audit("modify", f"REJECTED callable {key}")
            return "Error: cannot store callable values"
        err = self._validate_json_safe(value)
        if err:
            self._audit("modify", f"REJECTED {key}: {err}")
            return f"Error: {err}"
        if key not in self._loop._runtime_vars and len(self._loop._runtime_vars) >= self._MAX_RUNTIME_KEYS:
            self._audit("modify", f"REJECTED {key}: max keys ({self._MAX_RUNTIME_KEYS}) reached")
            return f"Error: _runtime_vars is full (max {self._MAX_RUNTIME_KEYS} keys). Reset unused keys first."
        old = self._loop._runtime_vars.get(key)
        self._loop._runtime_vars[key] = value
        self._audit("modify", f"_runtime_vars.{key}: {old!r} -> {value!r}")
        return f"Set _runtime_vars.{key} = {value!r}"

    @classmethod
    def _validate_json_safe(cls, value: Any, depth: int = 0, _elements: list[int] | None = None) -> str | None:
        if _elements is None:
            _elements = [0]
        if depth > 10:
            return "value nesting too deep (max 10 levels)"
        if isinstance(value, (str, int, float, bool, type(None))):
            return None
        if isinstance(value, list):
            _elements[0] += len(value)
            if _elements[0] > cls._MAX_VALUE_ELEMENTS:
                return f"value too large (max {cls._MAX_VALUE_ELEMENTS} total elements)"
            for i, item in enumerate(value):
                if err := cls._validate_json_safe(item, depth + 1, _elements):
                    return f"list[{i}] contains {err}"
            return None
        if isinstance(value, dict):
            _elements[0] += len(value)
            if _elements[0] > cls._MAX_VALUE_ELEMENTS:
                return f"value too large (max {cls._MAX_VALUE_ELEMENTS} total elements)"
            for k, v in value.items():
                if not isinstance(k, str):
                    return f"dict key must be str, got {type(k).__name__}"
                if err := cls._validate_json_safe(v, depth + 1, _elements):
                    return f"dict key '{k}' contains {err}"
            return None
        return f"unsupported type {type(value).__name__}"
